[[remember-me]]
= Remember-Me 认证
Doc Writer <tequlia2pop@gmail.com>
:toc: left
:homepage: http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#remember-me

[[remember-me-overview]]
== 概述

记住我（remember-me） 或持久登录（persistent-login）认证是指网站在会话中能够记住 principal 的身份。这通常通过向浏览器发送 cookie 来完成，在未来的会话期间可以检测到 cookie 并导致自动登录发生。Spring Security 为这些操作提供了必要的钩子，并有两个具体的 remember-me 实现。一种使用哈希来保持基于 cookie 的 token 的安全性，另一种使用数据库或其他持久存储机制来存储所生成的 token。

注意，两个实现都需要 `UserDetailsService`。如果你使用的认证提供程序没有使用 `UserDetailsService`（例如，LDAP 提供程序），那么它将无法工作，除非你的应用程序上下文中还有一个 `UserDetailsService` bean。

[[remember-me-hash-token]]
== 简单的基于哈希的 token 方式

这种方法使用哈希来实现有用的 remember-me 策略。本质上，在成功的交互式认证之后，cookie 被发送到浏览器，cookie 的组成如下：

[literal]
----
base64(username + ":" + expirationTime + ":" +
md5Hex(username + ":" + expirationTime + ":" password + ":" + key))

username:          As identifiable to the UserDetailsService
password:          That matches the one in the retrieved UserDetails
expirationTime:    The date and time when the remember-me token expires, expressed in milliseconds
key:               A private key to prevent modification of the remember-me token
----

因此，remember-me token 仅在指定的时间段有效，并且用户名，密码和私钥不会更改。值得注意的是，这具有潜在的安全性问题，因为从任何的用户代理捕获的 remember-me token 都可以使用，直到 token 到期为止。这是与 digest 认证相同的问题。如果 principal 知道已捕获的 token，他们可以容易地更改其密码，并立即使所有 remember-me token 失效。如果需要更重要的安全性，则应使用下一节中描述的方式。或者，应该根本不使用remember-me 服务。

如果您熟悉命名空间配置一章中讨论的主题，您可以通过添加 `<remember-me>` 元素启用 remember-me 身份验证：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
<http>
...
<remember-me key="myAppKey"/>
</http>
----

通常将自动选择 `UserDetailsService`。如果在应用程序上下文中有多个 `UserDetailsService`，那么需要使用 `user-service-ref` 属性指定要使用哪一个，属性值就是 `UserDetailsService` bean 的名称。

[[remember-me-persistent-token]]
== 持久化 token 方式

这种方式基于文章 http://jaspan.com/improved_persistent_login_cookie_best_practice 进行了一些小的修改.footnote:[基本上，用户名不包括在 cookie 中，以防止不必要地暴露有效的登录名。在本文的评论部分有一个讨论。]。要在命名空间配置中使用此方式，你需要提供一个数据源引用：

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
<http>
...
<remember-me data-source-ref="someDataSource"/>
</http>
----

数据库应包含使用以下 SQL（或等价物）创建的 `persistent_logins` 表：

[source,sql,indent=0]
[subs="verbatim,quotes"]
----
create table persistent_logins (username varchar(64) not null,
								series varchar(64) primary key,
								token varchar(64) not null,
								last_used timestamp not null)
----

[[remember-me-impls]]
== Remember-Me 接口和实现

Remember-me 与 `UsernamePasswordAuthenticationFilter` 一起使用，并通过 `AbstractAuthenticationProcessingFilter` 超类中的钩子实现。它也在 `BasicAuthenticationFilter` 中使用。钩子将在适当的时间调用一个具体的 `RememberMeServices`。接口如下所示：

[source,java,indent=0]
[subs="verbatim,quotes"]
----
Authentication autoLogin(HttpServletRequest request, HttpServletResponse response);

void loginFail(HttpServletRequest request, HttpServletResponse response);

void loginSuccess(HttpServletRequest request, HttpServletResponse response,
	Authentication successfulAuthentication);
----

要查看关于方法做什么的更全面的讨论，请参考 Javadoc，注意到在这个阶段 `AbstractAuthenticationProcessingFilter` 只调用了 `loginFail()` 和 `loginSuccess()` 方法。每当 `SecurityContextHolder` 不包含 `Authentication` 时，由 `RememberMeAuthenticationFilter` 调用 `autoLogin()` 方法。This interface therefore provides the underlying remember-me implementation with sufficient notification of authentication-related events, and delegates to the implementation whenever a candidate web request might contain a cookie and wish to be remembered. 这种设计允许任何数量的 remember-me 实现策略。我们上面已经看到 Spring Security 提供了两个实现。我们将依次看看这两个实现。

[[tokenbasedremembermeservices]]
=== TokenBasedRememberMeServices

[[persistenttokenbasedremembermeservices]]
=== PersistentTokenBasedRememberMeServices