= Spring Security Reference
Doc Writer <tequlia2pop@gmail.com>
:toc: left
:homepage: http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#jc

[[jc]]
== Java 配置

Spring 3.1 为 Spring 框架添加了对 http://docs.spring.io/spring/docs/3.1.x/spring-framework-reference/html/beans.html#beans-java[Java 配置] 的常规支持。自 Spring Security 3.2 开始支持 Spring Security Java 配置，使用户不使用任何 XML 就能够轻松地配置 Spring Security。

如果你熟悉 <<ns-config,Security 名称空间配置>>，那么你应该发现它和 Security Java 配置支持之间有几个相似之处。

NOTE: Spring Security 提供了 https://github.com/spring-projects/spring-security/tree/master/samples/javaconfig[大量示例的应用程序] 来演示 Spring Security Java 配置的使用。

=== Hello Web Security Java 配置

第一步是创建我们的 Spring Security Java 配置。该配置会创建一个名为 `springSecurityFilterChain` 的 Servlet filter，它负责应用程序所有的安全（保护应用程序 URL，验证提交的用户名和密码，重定向到登录表单等）。你可以在下面找到 Spring Security Java 配置的最基本的例子：

[[jc-hello-wsca]]
[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.context.annotation.*;
import org.springframework.security.config.annotation.authentication.builders.*;
import org.springframework.security.config.annotation.web.configuration.*;

@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Bean
	public UserDetailsService userDetailsService() throws Exception {
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(User.withUsername("user").password("password").roles("USER").build());
		return manager;
	}
}
----

你不需要做太多的配置，但实际上已经做了很多配置。你可以在下面找到功能的摘要：

* 需要对应用程序中的每个 URL 进行认证
* 生成登录表单
* 允许用户进行基于表单的认证（用户的**用户名**为 __user__，**密码**为 __password__）
* 允许用户退出
* 防止 http://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF 攻击]
* http://en.wikipedia.org/wiki/Session_fixation[Session Fixation] 保护
* Security Header integration
** http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[HTTP Strict Transport Security] for secure requests
** http://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx[X-Content-Type-Options] integration
** Cache Control (can be overridden later by your application to allow caching of your static resources)
** http://msdn.microsoft.com/en-us/library/dd565647(v=vs.85).aspx[X-XSS-Protection] integration
** X-Frame-Options integration to help prevent http://en.wikipedia.org/wiki/Clickjacking[Clickjacking]
* 与以下 Servlet API 方法集成
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[HttpServletRequest#getRemoteUser()]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[HttpServletRequest.html#getUserPrincipal()]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[HttpServletRequest.html#isUserInRole(java.lang.String)]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login(java.lang.String,%20java.lang.String)[HttpServletRequest.html#login(java.lang.String, java.lang.String)]
** http://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout()[HttpServletRequest.html#logout()]

==== AbstractSecurityWebApplicationInitializer

下一步是在 war 中注册 `springSecurityFilterChain`。在 Servlet 3.0+ 环境中，可以使用 http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-container-config[Spring 的 WebApplicationInitializer 支持] 的 Java 配置来完成。Spring Security 提供了一个基类 `AbstractSecurityWebApplicationInitializer`，它将确保为你注册 `springSecurityFilterChain`。使用 `AbstractSecurityWebApplicationInitializer` 的方式取决于我们是否使用了 Spring，或者 Spring Security 是否是我们应用程序中唯一的 Spring 组件。

* <<abstractsecuritywebapplicationinitializer-without-existing-spring>> - 如果你没有使用 Spring，请使用这些说明
* <<abstractsecuritywebapplicationinitializer-with-spring-mvc>> - 如果你使用了 Spring，请使用这些说明

==== 在非 Spring 项目中使用 AbstractSecurityWebApplicationInitializer

如果你没有使用 Spring 或 Spring MVC，你需要将 `WebSecurityConfig` 传入超类，以确保配置被选中。你可以找到下面的例子：

[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityWebApplicationInitializer
	extends AbstractSecurityWebApplicationInitializer {

	public SecurityWebApplicationInitializer() {
		super(WebSecurityConfig.class);
	}
}
----

`SecurityWebApplicationInitializer` 将执行以下操作：

* 为应用程序中的每个 URL 自动注册 springSecurityFilterChain filter
* 添加一个 ContextLoaderListener，它会加载 <<jc-hello-wsca,WebSecurityConfig>>。

==== 在 Spring MVC 中使用 AbstractSecurityWebApplicationInitializer

如果我们在应用程序的其他地方使用了 Spring，我们可能已经有一个 `WebApplicationInitializer` 来加载我们的 Spring 配置。如果我们使用前面的配置，我们会得到一个错误。相反，我们应该使用现有的 `ApplicationContext` 来注册 Spring Security。例如，如果我们正在使用 Spring MVC，我们的 `SecurityWebApplicationInitializer` 将类似于以下内容：

[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityWebApplicationInitializer
	extends AbstractSecurityWebApplicationInitializer {

}
----

这只会为你的应用程序中的每个 URL 注册 springSecurityFilterChain filter。之后，我们将确保在我们现有的 ApplicationInitializer 中加载 `WebSecurityConfig`。例如，如果我们正在使用 Spring MVC，可以在 `getRootConfigClasses()` 中添加它。

[[message-web-application-inititializer-java]]
[source,java]
----
public class MvcWebApplicationInitializer extends
		AbstractAnnotationConfigDispatcherServletInitializer {

	@Override
	protected Class<?>[] getRootConfigClasses() {
		return new Class[] { WebSecurityConfig.class };
	}

	// ... other overrides ...
}
----

[[jc-httpsecurity]]
=== HttpSecurity

Thus far our <<jc-hello-wsca,WebSecurityConfig>> only contains information about how to authenticate our users. How does Spring Security know that we want to require all users to be authenticated? How does Spring Security know we want to support form based authentication? The reason for this is that the `WebSecurityConfigurerAdapter` provides a default configuration in the `configure(HttpSecurity http)` method that looks like:

到目前为止，我们的 <<jc-hello-wsca,WebSecurityConfig>> 只包含了有关如何认证用户的信息。Spring Security 如何知道我们想要求对所有用户进行认证？ Spring Security 如何知道我们要支持基于表单的认证？ 其原因是 `WebSecurityConfigurerAdapter` 在 `configure(HttpSecurity http)` 方法中提供了一个默认的配置，如下所示：

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.anyRequest().authenticated()
			.and()
		.formLogin()
			.and()
		.httpBasic();
}
----

上面的默认配置：

* 确保应用程序的所有请求都需要对用户进行认证
* 允许用户使用基于表单的登录进行认证
* 允许用户使用 HTTP Basic 认证进行验证

你会注意到此配置与 XML 名称空间配置非常相似：

[source,xml]
----
<http>
	<intercept-url pattern="/**" access="authenticated"/>
	<form-login />
	<http-basic />
</http>
----

Java 配置使用的 `and()` 方法相当于 XML 的结束闭合标签，这允许我们继续配置其上一级（parent）。如果你查看代码，那么你会发现，我想配置授权的请求 __and__ 配置表单登录 __and_ 配置 HTTP Basic 认证。

但是，Java 配置具有不同的默认 URL 和参数。创建自定义登录页面时请记住这一点。结果是我们的 URL 更加 RESTful。此外，有一点不是很明显，我们使用 Spring Security 有助于防止 https://www.owasp.org/index.php/Information_Leak_(information_disclosure)[信息泄漏（information leaks）]。 例如：

[[jc-form]]
=== Java 配置和表单登录
你可能想知道提示登录时的登录表单来自哪里，因为我们没有提到任何的 HTML 文件或 JSP。由于 Spring Security 的默认配置没有显式地为登录页面设置 URL，Spring Security 会根据启用的功能自动生成一个 URL，并使用一个 URL 标准值来处理提交的登录，用户在登录后将使用的默认的目标 URL，等等。

虽然自动生成的登录页面对于快速启动和运行很方便，但大多数应用程序都想要提供自己的登录页面。为此，我们可以更新我们的配置，如下所示：


[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.anyRequest().authenticated()
			.and()
		.formLogin()
			.loginPage("/login") // <1>
			.permitAll();        // <2>
}
----

<1> 更新后的配置指定了登录页面的位置。
<2> 我们必须授予所有用户（例如未经认证的用户）访问登录页面的权限。`formLogin().permitAll()` 方法允许为所有用户授予与基于表单的登录相关联的所有 URL 的访问权限。

使用 JSP 实现的用于当前配置的示例登录页面如下所示：

NOTE: 下面的登录页面表示我们当前的配置。如果某些默认设置不能满足我们的需要，我们可以轻松地更新我们的配置。

[source,html]
----
<c:url value="/login" var="loginUrl"/>
<form action="${loginUrl}" method="post">       <1>
	<c:if test="${param.error != null}">        <2>
		<p>
			Invalid username and password.
		</p>
	</c:if>
	<c:if test="${param.logout != null}">       <3>
		<p>
			You have been logged out.
		</p>
	</c:if>
	<p>
		<label for="username">Username</label>
		<input type="text" id="username" name="username"/>	<4>
	</p>
	<p>
		<label for="password">Password</label>
		<input type="password" id="password" name="password"/>	<5>
	</p>
	<input type="hidden"                        <6>
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	<button type="submit" class="btn">Log in</button>
</form>
----

<1> 访问 `/login` URL 的 POST 请求将尝试认证用户
<2> 如果查询参数 `error` 存在，则认证失败
<3> 如果查询参数 `logout` 存在，表示用户已成功退出
<4> 名为 __username__ 的 HTTP 参数必须存在，它表示用户名
<5> 名为 __password__ 的 HTTP 参数必须存在，它表示密码，
<6> 我们必须 <<csrf-include-csrf-token,引入 CSRF token>>。要了解更多，请参阅参考的 <<csrf>> 部分。

[jc-authorize-requests]]
=== 对请求授权
我们的示例要求对应用程序中的每个 URL 都进行用户认证。我们可以通过向 `http.authorizeRequests()` 方法添加多个子节点来指定对 URL 的自定义要求。例如：


[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()                                                                <1>
			.antMatchers("/resources/**", "/signup", "/about").permitAll()                  <2>
			.antMatchers("/admin/**").hasRole("ADMIN")                                      <3>
			.antMatchers("/db/**").access("hasRole('ADMIN') and hasRole('DBA')")            <4>
			.anyRequest().authenticated()                                                   <5>
			.and()
		// ...
		.formLogin();
}
----

<1> `http.authorizeRequests()` 方法有多个子节点，每个 matcher 都按它们的声明顺序来发挥作用。
<2> 我们指定了用户可以访问的多个 URL pattern。具体来说，如果请求的 URL 以 "/resources/" 开头，等于 "/signup" 或等于 "/about"，则任何用户都可以访问这些请求。
<3> 以 "/admin/" 开头的任何 URL 将仅限于拥有角色 "ROLE_ADMIN" 的用户。你会注意到，由于我们调用了 `hasRole` 方法，我们不需要指定 "ROLE_" 前缀。
<4> 以 "/db/"  开头的任何 URL 都要求用户同时拥有 "ROLE_ADMIN" 和 "ROLE_DBA" 角色。你会注意到，由于我们使用 `hasRole` 表达式，我们不需要指定 "ROLE_" 前缀。
<5> 任何尚未匹配的 URL 只需要对用户进行认证

[[jc-logout]]
=== 处理退出

使用 `WebSecurityConfigurerAdapter` 时，会自动应用退出功能。默认情况下，访问 URL `/logout` 将会退出，并执行下列事项：

- 使 HTTP Session 失效
- 清除已配置的所有 RememberMe 认证
- 清除 `SecurityContextHolder`
- 重定向到 `/login?logout`

与配置登录功能类似，你还有各种选项可进一步自定义你退出的要求：

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.logout()                                                                    <1>
			.logoutUrl("/my/logout")                                                 <2>
			.logoutSuccessUrl("/my/index")                                           <3>
			.logoutSuccessHandler(logoutSuccessHandler)                              <4>
			.invalidateHttpSession(true)                                             <5>
			.addLogoutHandler(logoutHandler)                                         <6>
			.deleteCookies(cookieNamesToClear)                                       <7>
			.and()
		...
}
----

<1> 提供退出支持。在使用 `WebSecurityConfigurerAdapter` 时自动应用退出功能。
<2> 触发退出的 URL（默认为 `/logout`）。如果启用了 CSRF 防护（默认），则请求也必须是 POST。有关更多信息，请参阅 http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutUrl-java.lang.String-[JavaDoc]。
<3> 退出成功后重定向的 URL。默认值为 `/login?logout`。有关更多信息，请参阅 http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutSuccessUrl-java.lang.String-[JavaDoc]。
<4> 指定一个自定义的 `LogoutSuccessHandler`。如果指定了此参数，将忽略 `logoutSuccessUrl()`。有关更多内容，请参阅 http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutSuccessHandler-org.springframework.security.web.authentication.logout.LogoutSuccessHandler-[JavaDoc]。
<5> 指定在退出时是否使 HttpSession 失效。默认为 `true`。Configures the `SecurityContextLogoutHandler` under the covers.有关更多内容，请参阅 http://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#invalidateHttpSession-boolean-[JavaDoc]。
<6> 添加一个 `LogoutHandler`。默认情况下，`SecurityContextLogoutHandler` 作为最后一个 `LogoutHandler` 添加。
<7> 指定在退出成功时要删除的 Cookie 名称。这是显式添加 `CookieClearingLogoutHandler` 的快捷方式。

[NOTE]
====
当然，也可以使用 XML 名称空间符号来配置退出。有关更多详细信息，请参阅 Spring Security XML 名称空间的 <<nsa-logout,logout 元素>> 文档。
====

通常，为了定制退出功能，你可以添加 `{security-api-url}org/springframework/security/web/authentication/logout/LogoutHandler.html[LogoutHandler]` 和/或 `{security-api-url}org/springframework/security/web/authentication/logout/LogoutSuccessHandler.html[LogoutSuccessHandler]` 实现。For many common scenarios, these handlers are applied under the covers when using the fluent API.

[[jc-logout-handler]]
==== LogoutHandler

Generally, `{security-api-url}org/springframework/security/web/authentication/logout/LogoutHandler.html[LogoutHandler]`
implementations indicate classes that are able to participate in logout handling.
They are expected to be invoked to perform necessary cleanup. As such they should
not throw exceptions. Various implementations are provided:

- {security-api-url}org/springframework/security/web/authentication/rememberme/PersistentTokenBasedRememberMeServices.html[PersistentTokenBasedRememberMeServices]
- {security-api-url}org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServices.html[TokenBasedRememberMeServices]
- {security-api-url}org/springframework/security/web/authentication/logout/CookieClearingLogoutHandler.html[CookieClearingLogoutHandler]
- {security-api-url}org/springframework/security/web/csrf/CsrfLogoutHandler.html[CsrfLogoutHandler]
- {security-api-url}org/springframework/security/web/authentication/logout/SecurityContextLogoutHandler.html[SecurityContextLogoutHandler]

Please see <<remember-me-impls>> for details.

Instead of providing `LogoutHandler` implementations directly, the fluent API
also provides shortcuts that provide the respective `LogoutHandler` implementations
under the covers. E.g. `deleteCookies()` allows specifying the names of one or
more cookies to be removed on logout success. This is a shortcut compared to adding a
`CookieClearingLogoutHandler`.

[[jc-logout-success-handler]]
==== LogoutSuccessHandler

The `LogoutSuccessHandler` is called after a successful logout by the `LogoutFilter`,
to handle e.g. redirection or forwarding to the appropriate destination. Note that the
interface is almost the same as the `LogoutHandler` but may raise an exception.

The following implementations are provided:

- {security-api-url}org/springframework/security/web/authentication/logout/SimpleUrlLogoutSuccessHandler.html[SimpleUrlLogoutSuccessHandler]
- HttpStatusReturningLogoutSuccessHandler

As mentioned above, you don't need to specify the `SimpleUrlLogoutSuccessHandler` directly.
Instead, the fluent API provides a shortcut by setting the `logoutSuccessUrl()`.
This will setup the `SimpleUrlLogoutSuccessHandler` under the covers. The provided URL will
be redirected to after a logout has occurred. The default is `/login?logout`.

The `HttpStatusReturningLogoutSuccessHandler` can be interesting in REST API type
scenarios. Instead of redirecting to a URL upon the successful logout, this `LogoutSuccessHandler`
allows you to provide a plain HTTP status code to be returned. If not configured
a status code 200 will be returned by default.

[[jc-logout-references]]
==== 退出相关的进一步参考

- <<ns-logout, Logout Handling>>
- <<test-logout, Testing Logout>>
- <<servletapi-logout, HttpServletRequest.logout()>>
- <<remember-me-impls>>
- <<csrf-logout, Logging Out>> in section CSRF Caveats
- Section <<cas-singlelogout, Single Logout>> (CAS protocol)
- Documentation for the <<nsa-logout, logout element>> in the Spring Security XML Namespace section

[[jc-authentication]]
=== Authentication

到目前为止，我们只看了一下最基本的认证配置。让我们来看看一些稍微更高级的配置认证的选项。

[[jc-authentication-inmememory]]
==== 内存中的认证

我们已经看到为单个用户配置内存型认证的示例。以下是配置多个用户的示例：

[source,java]
----
@Bean
public UserDetailsService userDetailsService() throws Exception {
	InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
	manager.createUser(User.withUsername("user").password("password").roles("USER").build());
	manager.createUser(User.withUsername("admin").password("password").roles("USER","ADMIN").build());
	return manager;
}
----

[[jc-authentication-jdbc]]
==== JDBC 认证

你可以找到更新以支持基于 JDBC 的身份验证。下面的示例假设你已经在应用程序中定义了一个 DataSource。https://github.com/spring-projects/spring-security/tree/master/samples/javaconfig/jdbc[jdbc-javaconfig] 示例提供了使用基于 JDBC 的身份验证的完整示例。

[source,java]
----
@Autowired
private DataSource dataSource;

@Autowired
public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
	auth
		.jdbcAuthentication()
			.dataSource(dataSource)
			.withDefaultSchema()
			.withUser("user").password("password").roles("USER").and()
			.withUser("admin").password("password").roles("USER", "ADMIN");
}
----

==== LDAP Authentication

You can find the updates to suppport LDAP based authentication. The https://github.com/spring-projects/spring-security/tree/master/samples/javaconfig/ldap[ldap-javaconfig] sample provides a complete example of using LDAP based authentication.

[source,java]
----
@Autowired
private DataSource dataSource;

@Autowired
public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
	auth
		.ldapAuthentication()
			.userDnPatterns("uid={0},ou=people")
			.groupSearchBase("ou=groups");
}
----

The example above uses the following LDIF and an embedded Apache DS LDAP instance.

.users.ldif
----
dn: ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: organizationalUnit
ou: groups

dn: ou=people,dc=springframework,dc=org
objectclass: top
objectclass: organizationalUnit
ou: people

dn: uid=admin,ou=people,dc=springframework,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Rod Johnson
sn: Johnson
uid: admin
userPassword: password

dn: uid=user,ou=people,dc=springframework,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Dianne Emu
sn: Emu
uid: user
userPassword: password

dn: cn=user,ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: groupOfNames
cn: user
uniqueMember: uid=admin,ou=people,dc=springframework,dc=org
uniqueMember: uid=user,ou=people,dc=springframework,dc=org

dn: cn=admin,ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: groupOfNames
cn: admin
uniqueMember: uid=admin,ou=people,dc=springframework,dc=org
----

[[jc-authentication-authenticationprovider]]
==== AuthenticationProvider

You can define custom authentication by exposing a custom `AuthenticationProvider` as a bean.
For example, the following will customize authentication assuming that `SpringAuthenticationProvider` implements `AuthenticationProvider`:

NOTE: This is only used if the `AuthenticationManagerBuilder` has not been populated

[source,java]
----
@Bean
public SpringAuthenticationProvider springAuthenticationProvider() {
	return new SpringAuthenticationProvider();
}
----

[[jc-authentication-userdetailsservice]]
==== UserDetailsService

你可以定义自定义的认证，只需要将自定义的 `UserDetailsService` 公开为一个 bean。例如，下面将自定义认证，假设 `SpringDataUserDetailsService` 实现了 `UserDetailsService`：

NOTE: 这只有在没有填充 'AuthenticationManagerBuilder' 并且没有定义 'AuthenticationProviderBean' 的情况下才使用。

[source,java]
----
@Bean
public SpringDataUserDetailsService springDataUserDetailsService() {
	return new SpringDataUserDetailsService();
}
----

你还可以通过将 `PasswordEncoder` 公开为一个 bean 来自定义密码的转码方式。例如，如果使用 bcrypt，你可以添加一个 bean 定义，如下所示：

[source,java]
----
@Bean
public BCryptPasswordEncoder passwordEncoder() {
	return new BCryptPasswordEncoder();
}
----

==== LDAP Authentication

=== 多个 HttpSecurity

我们可以配置多个 HttpSecurity 实例，就像我们可以有多个 `<http>` 块一样。关键是要多次扩展 `WebSecurityConfigurationAdapter`。例如，以下是具有以 `/api/` 开头的 URL 的不同配置的示例。

[source,java]
----
@EnableWebSecurity                                                  <1>
public class MultiHttpSecurityConfig {
	@Bean
	public UserDetailsService userDetailsService() throws Exception {
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(User.withUsername("user").password("password").roles("USER").build());
		manager.createUser(User.withUsername("admin").password("password").roles("USER","ADMIN").build());
		return manager;
	}

	@Configuration
	@Order(1)                                                        <2>
	public static class ApiWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
		protected void configure(HttpSecurity http) throws Exception {
			http
				.antMatcher("/api/**")                               <3>
				.authorizeRequests()
					.anyRequest().hasRole("ADMIN")
					.and()
				.httpBasic();
		}
	}

	@Configuration                                                   <4>
	public static class FormLoginWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http
				.authorizeRequests()
					.anyRequest().authenticated()
					.and()
				.formLogin();
		}
	}
}
----

<1> 正常配置认证
<2> 创建包含 `@Order` 的 `WebSecurityConfigurerAdapter` 实例，以指定应首先考虑哪个 `WebSecurityConfigurerAdapter`。
<3> `http.antMatcher` 声明这个 `HttpSecurity` 只适用于以 `/api/` 开头的 URL
<4> 创建另一个 `WebSecurityConfigurerAdapter` 实例。如果 URL 不是以 `/api/` 开头，将使用此配置。在 `ApiWebSecurityConfigurationAdapter` 之后才会考虑这个配置，因为它在有一个大于 `1` 的 `@Order` 值（没有 `@Order` 注解的话默认为最后）。



[[jc-method]]
=== 方法安全

从 2.0 版本开始，Spring Security 已经大大提高了为服务层的方法添加安全性的支持。它提供了对 JSR-250 注解安全性以及框架原始的 `@Secured` 注解的支持。从 3.0 开始，你也可以使用新的 <<el-access,基于表达式的注解>>。你可以将安全性应用于单个 bean，使用 `intercept-methods` 元素装饰 bean 声明，也可以使用 AspectJ 样式的切入点在整个服务层上保护多个 bean。

==== EnableGlobalMethodSecurity

我们可以在任何 `@Configuration` 实例上使用 `@EnableGlobalMethodSecurity` 注解来启用基于注解的安全性。例如，以下将启用 Spring Security 的 `@Secured` 注解。

[source,java]
----
@EnableGlobalMethodSecurity(securedEnabled = true)
public class MethodSecurityConfig {
    // ...
}
----

向方法（在类或接口上）添加注解将相应地限制对该方法的访问。Spring Security 的原生注解支持为方法定义了一组属性。这些属性将被传递给 AccessDecisionManager，以便做出实际的决定：

[source,java]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----

可以使用下列代码启用对 JSR-250 注解的支持

[source,java]
----
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class MethodSecurityConfig {
    // ...
}
----

这些是基于标准的，允许应用简单的基于角色的约束，但没有 Spring Security 的原生注解那么强大。要使用新的基于表达式的语法，你可以使用

[source,java]
----
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig {
// ...
}
----

等效的 Java 代码为

[source,java]
----
public interface BankService {

@PreAuthorize("isAnonymous()")
public Account readAccount(Long id);

@PreAuthorize("isAnonymous()")
public Account[] findAccounts();

@PreAuthorize("hasAuthority('ROLE_TELLER')")
public Account post(Account account, double amount);
}
----

==== GlobalMethodSecurityConfiguration

有时，你可能需要执行比 `@EnableGlobalMethodSecurity` 注解允许的操作更复杂的操作。对于这些实例，你可以扩展 `GlobalMethodSecurityConfiguration`，确保 `@EnableGlobalMethodSecurity` 注解位于你的子类上。例如，如果你想提供一个自定义的 `MethodSecurityExpressionHandler`，你可以使用下面的配置：

[source,java]
----
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {
	@Override
	protected MethodSecurityExpressionHandler createExpressionHandler() {
		// ... create and return custom MethodSecurityExpressionHandler ...
		return expressionHandler;
	}
}
----

有关可以覆盖的方法的其他信息，请参阅 `GlobalMethodSecurityConfiguration` Javadoc。

=== Post Processing Configured Objects

Spring Security 的 Java 配置没有公开它配置的每个对象的每个属性。这简化了大多数用户的配置。总之，如果把每个属性都暴露出来，用户可以使用标准的 bean 配置。

虽然有很好的理由不直接暴露每个属性，用户可能仍需要更高级的配置选项。为了解决这个问题，Spring Security 引入了一个 `ObjectPostProcessor` 的概念，它可以用于修改或替换由 Java 配置创建的多个 Object 实例。例如，如果你想在 `FilterSecurityInterceptor`上配置 `filterSecurityPublishAuthorizationSuccess` 属性，你可以使用以下命令：

[source,java]
----
@Override
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests()
			.anyRequest().authenticated()
			.withObjectPostProcessor(new ObjectPostProcessor<FilterSecurityInterceptor>() {
				public <O extends FilterSecurityInterceptor> O postProcess(
						O fsi) {
					fsi.setPublishAuthorizationSuccess(true);
					return fsi;
				}
			});
}
----

[[jc-custom-dsls]]
=== Custom DSLs

You can provide your own custom DSLs in Spring Security.
For example, you might have something that looks like this:

[source,java]
----
public class MyCustomDsl extends AbstractHttpConfigurer<CorsConfigurerMyCustomDsl, HttpSecurity> {
	private boolean flag;

	@Override
	public void init(H http) throws Exception {
		// any method that adds another configurer
		// must be done in the init method
		http.csrf().disable();
	}

	@Override
	public void configure(H http) throws Exception {
		ApplicationContext context = http.getSharedObject(ApplicationContext.class);

		// here we lookup from the ApplicationContext. You can also just create a new instance.
		MyFilter myFilter = context.getBean(MyFilter.class);
		myFilter.setFlag(flag);
		http.addFilterBefore(myFilter, UsernamePasswordAuthenticationFilter.class);
	}

	public MyCustomDsl flag(boolean value) {
		this.flag = value;
		return this;
	}

	public static MyCustomDsl customDsl() {
		return new MyCustomDsl();
	}
}
----

NOTE: This is actually how methods like `HttpSecurity.authorizeRequests()` are implemented.

The custom DSL can then be used like this:

[source,java]
----
@EnableWebSecurity
public class Config extends WebSecurityConfigurerAdapter {
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.apply(customDsl())
				.flag(true)
				.and()
			...;
	}
}
----

The code is invoked in the following order:

* Code in `Config`s configure method is invoked
* Code in `MyCustomDsl`s init method is invoked
* Code in `MyCustomDsl`s configure method is invoked

If you want, you can have `WebSecurityConfiguerAdapter` add `MyCustomDsl` by default by using `SpringFactories`.
For example, you would create a resource on the classpath named `META-INF/spring.factories` with the following contents:

.META-INF/spring.factories
----
org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer = sample.MyCustomDsl
----

Users wishing to disable the default can do so explicitly.

[source,java]
----
@EnableWebSecurity
public class Config extends WebSecurityConfigurerAdapter {
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.apply(customDsl()).disable()
			...;
	}
}
----